version: '3'
services:
  elasticsearch:
    image: my-elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:

networks:
  default:
    driver: bridge
